# Copyright 2021 The Rethnet Authors.
# Licensed under the Apache License, Version 2.0.

[package]
name = "rethnet"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
authors = ["Karim Agha <karim.dev@gmail.com>"]

[lib]
name = "rethnet"
path = "src/lib.rs"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
napi = { version = "1.7.5", optional = true }
napi-derive = { version = "1.1.0", optional = true }
evmodin = { git = "https://github.com/nomiclabs/evmodin.git?branch=master" }

[dev-dependencies]
hex-literal = "0.3.3"

[build-dependencies]
napi-build = "1.1.0"

[features]
nodejs = ["napi", "napi-derive"]

# TODO: consider disabling nodejs by default unless requested.
default = ["nodejs"]