# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright 2021 contributors to the Rethnet project.

[package]
name = "rethnet"
version = "0.1.0"
edition = "2018"
license = "MIT"
authors = ["Karim Agha <karim.dev@gmail.com>"]

[dependencies]
bytes = "1.0.1"
ethereum-types = { version = "0.12" }
evmodin = { git = "https://github.com/nomiclabs/evmodin.git?branch=master" }

[dev-dependencies]
anyhow = "1.0.42"
hex-literal = "0.3.3"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[workspace]
members = [".", "jsonrpc", "nodejs"]
default-members = ["."]